### ISSUE TITLE
Fall 2017 Event - Preliminary Quality Review

### ISSUE THREAD

**Issue by dudleycodes** [LacledesLAN/gamesvr-blackmesa-freeplay#1]
- [x] Update MM / SM to latest
- [x] Make sure linux files are in `dist.linux` and that generic files are in `dist`
- [x] Verify advertisements works
- [x] Verify `sm_admin` works
- [x] Verify MOTD works
- [x] Verify your custom plugin is installed and working (dumps info to console on startup)
- [x] Verify LL config is loading
- [x] Verify map voting is enabled

When testing use image name of `lacledeslan/gamesvr-blackmesa-freeplay` (`-srcds` and `:linux` are no longer necessary).

**Comment by JustinBenedick** [comment]
Updated sm/mm and sorted files  2b4706c

**Comment by dudleycodes** [comment]
@JustinBenedick how's this going?

**Comment by dudleycodes** [comment]
What's the word on this @JustinBenedick?

**Comment by JustinBenedick** [comment]
MOTD Doesn't show,  not even a default one. Ads need some tweaks, map voting needs to be enabled. 

24b5801

**Comment by JustinBenedick** [comment]
all fixed, all good  4320602
